mainmenu:
- identifier: 35abb102-b678-4965-9f7a-bc9aced8a536
  name: m1
  pageRef: /pages/p1
  weight: 10
- identifier: fe3305f1-028d-4ced-aaaa-bdc85b8e5e1a
  name: m2
  pageRef: /external-resources/er2
  weight: 20
